### PR TITLE
pyproject.toml: Move metadata, setuptools config here from setup.cfg

### LINKED ISSUE #32: Version 0.8.9 commit is not on the master branch
https://github.com/sagemath/pplpy/commit/2218709b97a11ec87bacddae354aa682e483626b

### PR DESCRIPTION
**Pull request by mkoeppe**
Based on the loose tag 0.8.9 
- Fixes #32

### CODE REVIEW

**Comment by mkoeppe** [comment]
@videlec I don't know why the "link checker" is not feeling well, but apart from this, this is ready

**Comment by videlec** [comment]
I am having a look.

**Comment by videlec** [comment]
Apparently, the link checker correctly detects two redirections
```
URL        `https://pypi.python.org/pypi/pplpy/'
Name       `Python Package Index'
Parent URL http://localhost:8880/pplpy/, line 43, col 32
Real URL   https://pypi.org/project/pplpy/
Check time 3.129 seconds
Size       10.28KB
Warning    [http-redirected] Redirected to
           `https://pypi.org/pypi/pplpy/' status: 301 Redirect to
           Primary Domain.
           [http-redirected] Redirected to
           `https://pypi.org/project/pplpy/' status: 301 Moved
           Permanently.
Result     Valid: 200 OK

URL        `https://www.sphinx-doc.org/'
Name       `Sphinx'
Parent URL http://localhost:8880/pplpy/, line 5220, col 21
Real URL   https://www.sphinx-doc.org/en/master/
Check time 2.280 seconds
Warning    [http-redirected] Redirected to
           `https://www.sphinx-doc.org/en/master/' status: 302
           Found.
Result     Valid: 200 OK
```

**Comment by mkoeppe** [comment]
I'd say that Download link is redundant, do you want me to just remove it?

**Comment by videlec** [comment]
You mean the one in the readme?

**Comment by mkoeppe** [comment]
I've fixed some links. Not sure where the remaining warning is coming from. Sphinx itself?
```
URL        `https://www.sphinx-doc.org/'
Name       `Sphinx'
Parent URL http://localhost:8880/pplpy/, line 5220, col 21
Real URL   https://www.sphinx-doc.org/en/master/
Check time 2.485 seconds
Warning    [http-redirected] Redirected to
           `https://www.sphinx-doc.org/en/master/' status: 302
           Found.
```

**Comment by videlec** [comment]
I think that it comes from sphinx itself (I already saw that in another project). As a workaround there is a `--ignore-url` option to the link checker.

**Comment by videlec** [comment]
Actually, this project was pplpy itself, see 29 :-)

**Comment by mkoeppe** [comment]
I don't understand.

Is there something I should still fix here, or can it be merged?

**Comment by videlec** [comment]
It is most likely that #29 conflicts with this PR. I will proceed with the merge and fix conflicts.

Thanks for the PR.

**Comment by mkoeppe** [comment]
I've done the merged here for your convenience

**Comment by videlec** [comment]
Wonderful. Thanks.

**Pull request merged**
