### PR TITLE
Add compatibility with Python 3.12

### PR DESCRIPTION
**Pull request by tobiasdiez**
Not sure if its that easy.

### CODE REVIEW

**Comment by videlec** [comment]
Not that easy indeed. One needs to first upgrade packages on conda-forge (see https://github.com/conda-forge/gmpy2-feedstock/pull/35).
```console
Run mamba install --quiet setuptools gmpy2 cysignals ppl "cython<3.0.0"
Could not solve for environment specs
The following packages are incompatible
└─ gmpy2   is installable with the potential options
   ├─ gmpy2 [2.0.7|2.0.8|2.1.0b1] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;
   ├─ gmpy2 [2.0.7|2.0.8] would require
   │  └─ python 3.4* , which can be installed;
   ├─ gmpy2 [2.0.7|2.0.8] would require
   │  └─ python 3.5* , which can be installed;
   ├─ gmpy2 2.0.8 would require
   │  └─ python 3.6* , which can be installed;
   ├─ gmpy2 [2.0.8|2.1.0b1|2.1.0b5] would require
   │  └─ python >=3.6,<3.7.0a0 , which can be installed;
   ├─ gmpy2 [2.0.8|2.1.0b1|2.1.0b5|2.1.0rc1|2.1.2] would require
   │  └─ python >=3.7,<3.8.0a0 , which can be installed;
   ├─ gmpy2 [2.1.0b1|2.1.0b5|2.1.0rc1|2.1.2] would require
   │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   ├─ gmpy2 [2.1.0b1|2.1.0b5|2.1.0rc1|2.1.2] would require
   │  └─ python >=3.9,<3.10.0a0 , which can be installed;
   ├─ gmpy2 [2.1.0rc1|2.1.2] would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   └─ gmpy2 2.1.2 would require
      └─ python >=3.11,<3.12.0a0 , which can be installed.
```

**Comment by mkoeppe** [comment]
Yes, gmpy2 is not ready. See https://github.com/sagemath/sage/pull/36351

**Comment by videlec** [comment]
> Yes, gmpy2 is not ready. See [sagemath/sage#36351](https://github.com/sagemath/sage/pull/36351)

Thanks for the pointer. There is an [alpha release](https://github.com/aleaxit/gmpy/releases/tag/gmpy2-2.2.0a1) that we could use here.

**Comment by videlec** [comment]
conclusion: nothing to do :-)

**Pull request merged**
